//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BaseCalculator.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BASECALCULATOR_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       133
#define IDD_DIALOG_BASE                 135
#define IDD_DIALOG_ENGINEERING          137
#define IDB_PNG_TIMELINE_NOMAL          143
#define IDB_PNG_TIMELINE_HOVER          145
#define IDB_PNG_TIMELINE_DOWN           146
#define IDD_DIALOG_TIMELINE             147
#define IDB_PNG_TRASH_NOMAL             149
#define IDB_PNG_TRASH_HOVER             150
#define IDB_PNG_TRASH_DOWN              151
#define IDB_PNG_BASE_NOMAL              152
#define IDB_PNG_ENGINEERING             153
#define IDB_PNG_ENGINEERING_NOMAL       153
#define IDD_DIALOG_CONVERTER            154
#define IDB_PNG_CONVERTER_NOMAL         157
#define IDB_PNG_TIME_NOMAL              158
#define IDD_DIALOG_TIME                 159
#define IDD_DIALOG_DATE                 159
#define IDD_DIALOG_STOPWATCH            161
#define IDB_PNG_TIMER                   163
#define IDB_PNG_TIMER_NOMAL             163
#define IDB_PNG_STOPWATCH_NOMAL         163
#define IDD_TAB_LENGTH                  166
#define IDD_TAB_WEIGHT                  168
#define IDD_TAB_WIDTH                   170
#define IDD_TAB_TIME                    172
#define IDD_TAB_BIT                     174
#define IDB_PNG_BIT_NOMAL               182
#define IDB_PNG_LENGTH_NOMAL            183
#define IDB_PNG_TIMEC_NOMAL             184
#define IDB_PNG_WEIGHT_NOMAL            185
#define IDB_PNG_WIDTH_NOMAL             186
#define IDB_PNG_REVERSE_NOMAL           189
#define IDB_PNG_TIMER1_NOMAL            190
#define IDD_DIALOG_TIMER                191
#define IDC_INPUT_10_FROM2              1000
#define IDC_INPUT_2_FROM2               1001
#define IDC_OUTPUT_2_FROM2              1002
#define IDC_OUTPUT_10_FROM2             1003
#define IDC_BUTTON_RESULT_TWO_FROM2     1004
#define IDC_BUTTON_RESULT_TEN_FROM2     1005
#define IDC_INPUT_10_FROM16             1007
#define IDC_OUTPUT_16_FROM16            1008
#define IDC_INPUT_16_FROM16             1009
#define IDC_OUTPUT_10_FROM16            1010
#define IDC_BUTTON_RESULT_SIXTEEN_FROM16 1011
#define IDC_BUTTON_RESULT_TEN_FROM16    1012
#define IDC_COMBO_SELECT                1013
#define IDC_STATIC_OUTPUT_SELECT        1014
#define IDC_STATIC_OUTPUT_RESULT        1014
#define IDC_STATIC_INPUT_SELECT         1015
#define IDC_COMBO_RESULT                1016
#define IDC_BUTTON_BASE                 1020
#define IDC_BUTTON_CALCULATOR           1021
#define IDC_MFCBUTTON1                  1022
#define IDC_BUTTON_REPORT               1022
#define IDC_BUTTON_CONVERTER            1022
#define IDC_BUTTON_STARTANDSTOP         1022
#define IDC_BUTTON_AFTERDATE            1022
#define IDC_BUTTON_LENGTH               1022
#define IDC_BUTTON_ICON_BIT             1022
#define IDC_BUTTON_ICON_TIME            1022
#define IDC_BUTTON_ICON_WEIGHT          1022
#define IDC_BUTTON_ICON_WIDTH           1022
#define IDC_BUTTON_WORK_HOUR_UP         1022
#define IDC_BUTTON_CLEAR                1023
#define IDC_BUTTON_TIME                 1023
#define IDC_MFCBUTTON2                  1023
#define IDC_BUTTON_RESET                1023
#define IDC_BUTTON_DATE                 1023
#define IDC_BUTTON_LIMITDATE            1023
#define IDC_BUTTON_WIDTH                1023
#define IDC_BUTTON_ICON_LENGTH          1023
#define IDC_BUTTON_CONTAINER2           1023
#define IDC_BUTTON_WORK_HOUR_DOWN       1023
#define IDC_BUTTON_BACK                 1024
#define IDC_BUTTON_TIMER                1024
#define IDC_BUTTON_WEIGHT               1024
#define IDC_BUTTON_HOUR_TEST            1024
#define IDC_BUTTON_STOPWATCH            1024
#define IDC_BUTTON_WORK_MINUTE_UP       1024
#define IDC_BUTTON_TIMEC                1025
#define IDC_BUTTON_MINUTE_TEST          1025
#define IDC_BUTTON_DATE2                1025
#define IDC_BUTTON_TIMER1               1025
#define IDC_BUTTON_WORK_MINUTE_DOWN     1025
#define IDC_BUTTON_SECOND_TEST          1026
#define IDC_BUTTON_WORK_SECOND_UP       1026
#define IDC_BUTTON_WORK_SECOND_DOWN     1027
#define IDC_BUTTON_REST_HOUR_UP         1028
#define IDC_BUTTON_REST_HOUR_DOWN       1029
#define IDC_BUTTON_REST_MINUTE_UP       1030
#define IDC_BUTTON_REST_MINUTE_DOWN     1031
#define IDC_BUTTON_REST_SECOND_UP       1032
#define IDC_BUTTON_REST_SECOND_DOWN     1033
#define IDC_BUTTON_DIVIDE               1035
#define IDC_BUTTON_MULTI                1036
#define IDC_BUTTON_SUM                  1037
#define IDC_BUTTON_MIN                  1038
#define IDC_BUTTON_RESULT               1039
#define IDC_BUTTON_DOT                  1040
#define IDC_EDIT_CALCULATE_VIEW         1041
#define IDC_BUTTON_OPENBRACKET          1042
#define IDC_EDIT_RESULT                 1043
#define IDC_BUTTON_CLOSEBRACKET         1044
#define IDC_BUTTON_EXPONENTIATION       1045
#define IDC_BUTTON_REMAINER             1046
#define IDC_BUTTON_ROOT                 1047
#define IDC_BUTTON_FACTORIAL            1048
#define IDC_BUTTON_TRASH                1049
#define IDC__STATIC_CALCULATE_VIEW      1050
#define IDC_STATIC_BASE                 1054
#define IDC_STATIC_ENGINEERING          1055
#define IDC_STATIC_ENGINEERING2         1056
#define IDC_STATIC_CONVERTER            1056
#define IDC_STATIC_TIMER_VIEW           1056
#define IDC_STATIC_TIME                 1057
#define IDC_STATIC_HMS                  1057
#define IDC_STATIC_DATE                 1057
#define IDC_STATIC_TIMER                1058
#define IDC_STATIC_MILS                 1058
#define IDC_STATIC_STOPWATCH            1058
#define IDC_STATIC_DATE2                1059
#define IDC_STATIC_TIMER1               1059
#define IDC_MONTHCALENDAR               1064
#define IDC_EDIT_BASEDATE               1065
#define IDC_EDIT_AFTER_DATE             1066
#define IDC_EDIT_LIMIT_DATE             1067
#define IDC_EDIT_AFTERDATE_RESULT       1068
#define IDC_EDIT_LIMITDATE_RESULT       1069
#define IDC_BUTTON_FOCUS                1071
#define IDC_BUTTON_ALLRESET             1072
#define IDC_STATIC22                    1073
#define IDC_GROUP_LIMITDATE             1073
#define IDC_GROUP_AFTERDATE             1074
#define IDC_BUTTON_BIT                  1077
#define IDC_STATIC_TAB                  1078
#define IDC_BUTTON_COMBO                1081
#define IDC_COMBO_LEFT                  1083
#define IDC_COMBO_RIGHT                 1084
#define IDC_EDIT_LEFT_VALUE             1085
#define IDC_EDIT_RIGHT_VALUE            1086
#define IDC_EDIT_LEFT_VALUE5            1086
#define IDC_EDIT_HOUR                   1086
#define IDC_STATIC_MM                   1087
#define IDC_STATIC_CM                   1088
#define IDC_STATIC_M                    1089
#define IDC_STATIC_KM                   1090
#define IDC_STATIC_IN                   1091
#define IDC_STATIC_FT                   1092
#define IDC_STATIC_YD                   1093
#define IDC_STATIC_MILES                1094
#define IDC_STATIC_JA                   1095
#define IDC_STATIC_GAN                  1096
#define IDC_STATIC_JUNG                 1097
#define IDC_STATIC_LEE                  1098
#define IDC_STATIC_HAELEE               1099
#define IDC_BUTTON_COMBO2               1100
#define IDC_EDIT_LEFT_VALUE6            1100
#define IDC_EDIT_MINUTE                 1100
#define IDC_EDIT_LEFT_VALUE2            1101
#define IDC_EDIT_RIGHT_VALUE2           1102
#define IDC_COMBO_LEFT2                 1103
#define IDC_COMBO_RIGHT2                1104
#define IDC_STATIC_SQUAREDM             1105
#define IDC_STATIC_ARE                  1106
#define IDC_STATIC_HECTARE              1107
#define IDC_STATIC_SQUAREDKM            1108
#define IDC_STATIC_SQUAREDFT            1109
#define IDC_STATIC_SQUAREDYD            1110
#define IDC_STATIC_ACRE                 1111
#define IDC_STATIC_SQUARERULER          1112
#define IDC_STATIC_SQUARE               1113
#define IDC_STATIC_DANBO                1114
#define IDC_STATIC_JUNGBO               1115
#define IDC_STATIC_GUAN                 1116
#define IDC_BUTTON_COMBO3               1117
#define IDC_EDIT_LEFT_VALUE3            1118
#define IDC_EDIT_RIGHT_VALUE3           1119
#define IDC_BUTTON_CONTAINER3           1120
#define IDC_COMBO_LEFT3                 1121
#define IDC_COMBO_RIGHT3                1122
#define IDC_STATIC_MG                   1123
#define IDC_STATIC_G                    1124
#define IDC_STATIC_KG                   1125
#define IDC_STATIC_T                    1126
#define IDC_STATIC_KT                   1127
#define IDC_STATIC_GR                   1128
#define IDC_STATIC_OZ                   1129
#define IDC_STATIC_LB                   1130
#define IDC_STATIC_DON                  1131
#define IDC_STATIC_NYANG                1132
#define IDC_STATIC_GEUN                 1133
#define IDC_BUTTON_COMBO4               1134
#define IDC_COMBO_LEFT4                 1135
#define IDC_COMBO_RIGHT4                1136
#define IDC_BUTTON_CONTAINER            1137
#define IDC_EDIT_LEFT_VALUE4            1138
#define IDC_EDIT_RIGHT_VALUE4           1139
#define IDC_STATIC_BIT                  1140
#define IDC_STATIC_BYTE                 1141
#define IDC_STATIC_KBYTE                1142
#define IDC_STATIC_MBYTE                1143
#define IDC_STATIC_GBYTE                1144
#define IDC_STATIC_TBYTE                1145
#define IDC_STATIC_PBTYE                1146
#define IDC_STATIC_EBYTE                1147
#define IDC_BUTTON_REVERSE              1148
#define IDC_BUTTON_REVERSE2             1149
#define IDC_BUTTON_REVERSE3             1150
#define IDC_BUTTON_REVERSE4             1151
#define IDC_EDIT_DATE                   1152
#define IDC_EDIT_SECOND                 1153
#define IDC_BUTTON_DATE_TEST            1154
#define IDC_BUTTON_RESET_TIME           1155
#define IDC_STATIC_DHMS_TIME            1156
#define IDC_STATIC_MS_TIME              1158
#define IDC_STATIC_S_TIME               1159
#define IDC_STATIC_HMS_TIME             1160
#define IDC_BUTTON_CONTAINER4           1161
#define IDC_STATIC_DIVIDE               1162
#define IDC_STATIC_DIVIDE2              1163
#define IDC_STATIC_DIVIDE3              1164
#define IDC_STATIC_DIVIDE4              1165
#define IDC_STATIC_DIVIDE5              1166
#define IDC_EDIT_WORK_HOUR1             1167
#define IDC_EDIT_WORK_HOUR2             1168
#define IDC_EDIT_WORK_MINUTE1           1169
#define IDC_EDIT_WORK_MINUTE2           1170
#define IDC_EDIT_WORK_SECOND1           1171
#define IDC_EDIT_WORK_SECOND2           1172
#define IDC_EDIT_REST_HOUR1             1173
#define IDC_EDIT_REST_HOUR2             1174
#define IDC_EDIT_REST_MINUTE1           1175
#define IDC_EDIT_REST_MINUTE2           1176
#define IDC_EDIT_REST_SECOND1           1177
#define IDC_EDIT_REST_SECOND2           1178
#define IDC_BUTTON_STARTANDSTOP2        1179
#define IDC_BUTTON_RESET2               1180
#define IDC_BUTTON_0                    2000
#define IDC_BUTTON_1                    2001
#define IDC_BUTTON_2                    2002
#define IDC_BUTTON_3                    2003
#define IDC_BUTTON_4                    2004
#define IDC_BUTTON_5                    2005
#define IDC_BUTTON_6                    2006
#define IDC_BUTTON_7                    2007
#define IDC_BUTTON_8                    2008
#define IDC_BUTTON_9                    2009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1181
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
