//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BaseCalculator.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BASECALCULATOR_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       133
#define IDD_DIALOG_BASE                 135
#define IDD_DIALOG_ENGINEERING          137
#define IDB_PNG_TIMELINE_NOMAL          143
#define IDB_PNG_TIMELINE_HOVER          145
#define IDB_PNG_TIMELINE_DOWN           146
#define IDD_DIALOG_TIMELINE             147
#define IDB_PNG_TRASH_NOMAL             149
#define IDB_PNG_TRASH_HOVER             150
#define IDB_PNG_TRASH_DOWN              151
#define IDB_PNG_BASE_NOMAL              152
#define IDB_PNG_ENGINEERING             153
#define IDB_PNG_ENGINEERING_NOMAL       153
#define IDD_DIALOG_CONVERTER            154
#define IDB_PNG_CONVERTER_NOMAL         157
#define IDB_PNG_TIME_NOMAL              158
#define IDD_DIALOG_TIME                 159
#define IDD_DIALOG_DATE                 159
#define IDD_DIALOG_STOPWATCH            161
#define IDB_PNG_TIMER                   163
#define IDB_PNG_TIMER_NOMAL             163
#define IDD_TAB_LENGTH                  166
#define IDD_TAB_WEIGHT                  168
#define IDD_TAB_WIDTH                   170
#define IDD_TAB_TIME                    172
#define IDD_TAB_BIT                     174
#define IDB_PNG_BIT_NOMAL               182
#define IDB_PNG_LENGTH_NOMAL            183
#define IDB_PNG_TIMEC_NOMAL             184
#define IDB_PNG_WEIGHT_NOMAL            185
#define IDB_PNG_WIDTH_NOMAL             186
#define IDC_INPUT_10_FROM2              1000
#define IDC_INPUT_2_FROM2               1001
#define IDC_OUTPUT_2_FROM2              1002
#define IDC_OUTPUT_10_FROM2             1003
#define IDC_BUTTON_RESULT_TWO_FROM2     1004
#define IDC_BUTTON_RESULT_TEN_FROM2     1005
#define IDC_INPUT_10_FROM16             1007
#define IDC_OUTPUT_16_FROM16            1008
#define IDC_INPUT_16_FROM16             1009
#define IDC_OUTPUT_10_FROM16            1010
#define IDC_BUTTON_RESULT_SIXTEEN_FROM16 1011
#define IDC_BUTTON_RESULT_TEN_FROM16    1012
#define IDC_COMBO_SELECT                1013
#define IDC_STATIC_OUTPUT_SELECT        1014
#define IDC_STATIC_OUTPUT_RESULT        1014
#define IDC_STATIC_INPUT_SELECT         1015
#define IDC_COMBO_RESULT                1016
#define IDC_BUTTON_BASE                 1020
#define IDC_BUTTON_CALCULATOR           1021
#define IDC_MFCBUTTON1                  1022
#define IDC_BUTTON_REPORT               1022
#define IDC_BUTTON_CONVERTER            1022
#define IDC_BUTTON_STARTANDSTOP         1022
#define IDC_BUTTON_AFTERDATE            1022
#define IDC_BUTTON_LENGTH               1022
#define IDC_BUTTON_ICON_BIT             1022
#define IDC_BUTTON_ICON_TIME            1022
#define IDC_BUTTON_ICON_WEIGHT          1022
#define IDC_BUTTON_ICON_WIDTH           1022
#define IDC_BUTTON_TEST                 1022
#define IDC_BUTTON_CLEAR                1023
#define IDC_BUTTON_TIME                 1023
#define IDC_MFCBUTTON2                  1023
#define IDC_BUTTON_RESET                1023
#define IDC_BUTTON_DATE                 1023
#define IDC_BUTTON_LIMITDATE            1023
#define IDC_BUTTON_WIDTH                1023
#define IDC_BUTTON_ICON_LENGTH          1023
#define IDC_BUTTON_BACK                 1024
#define IDC_BUTTON_TIMER                1024
#define IDC_BUTTON_WEIGHT               1024
#define IDC_BUTTON_7                    1025
#define IDC_BUTTON_TIMEC                1025
#define IDC_BUTTON_8                    1026
#define IDC_BUTTON_9                    1027
#define IDC_BUTTON_4                    1028
#define IDC_BUTTON_1                    1029
#define IDC_BUTTON_5                    1030
#define IDC_BUTTON_2                    1031
#define IDC_BUTTON_6                    1032
#define IDC_BUTTON_3                    1033
#define IDC_BUTTON_0                    1034
#define IDC_BUTTON_DIVIDE               1035
#define IDC_BUTTON_MULTI                1036
#define IDC_BUTTON_SUM                  1037
#define IDC_BUTTON_MIN                  1038
#define IDC_BUTTON_RESULT               1039
#define IDC_BUTTON_DOT                  1040
#define IDC_EDIT_CALCULATE_VIEW         1041
#define IDC_BUTTON_OPENBRACKET          1042
#define IDC_EDIT_RESULT                 1043
#define IDC_BUTTON_CLOSEBRACKET         1044
#define IDC_BUTTON_EXPONENTIATION       1045
#define IDC_BUTTON_REMAINER             1046
#define IDC_BUTTON_ROOT                 1047
#define IDC_BUTTON_FACTORIAL            1048
#define IDC_BUTTON_TRASH                1049
#define IDC__STATIC_CALCULATE_VIEW      1050
#define IDC_STATIC_BASE                 1054
#define IDC_STATIC_ENGINEERING          1055
#define IDC_STATIC_ENGINEERING2         1056
#define IDC_STATIC_CONVERTER            1056
#define IDC_STATIC_TIMER_VIEW           1056
#define IDC_STATIC_TIME                 1057
#define IDC_STATIC_HMS                  1057
#define IDC_STATIC_DATE                 1057
#define IDC_STATIC_TIMER                1058
#define IDC_STATIC_MILS                 1058
#define IDC_MONTHCALENDAR               1064
#define IDC_EDIT_BASEDATE               1065
#define IDC_EDIT_AFTER_DATE             1066
#define IDC_EDIT_LIMIT_DATE             1067
#define IDC_EDIT_AFTERDATE_RESULT       1068
#define IDC_EDIT_LIMITDATE_RESULT       1069
#define IDC_BUTTON_FOCUS                1071
#define IDC_BUTTON_ALLRESET             1072
#define IDC_STATIC22                    1073
#define IDC_GROUP_LIMITDATE             1073
#define IDC_GROUP_AFTERDATE             1074
#define IDC_BUTTON_BIT                  1077
#define IDC_STATIC_TAB                  1078
#define IDC_BUTTON_COMBO                1081
#define IDC_COMBO_LEFT                  1083
#define IDC_COMBO_RIGHT                 1084
#define IDC_EDIT_LEFT_VALUE             1085
#define IDC_EDIT_RIGHT_VALUE            1086
#define IDC_STATIC_MM                   1087
#define IDC_STATIC_CM                   1088
#define IDC_STATIC_M                    1089
#define IDC_STATIC_KM                   1090
#define IDC_STATIC_IN                   1091
#define IDC_STATIC_FT                   1092
#define IDC_STATIC_YD                   1093
#define IDC_STATIC_MILES                1094
#define IDC_STATIC_JA                   1095
#define IDC_STATIC_GAN                  1096
#define IDC_STATIC_JUNG                 1097
#define IDC_STATIC_LEE                  1098
#define IDC_STATIC_HAELEE               1099

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
